/**
 * Document Generation Service
 * Handles generation of legal documents for property management:
 * - Rent receipts (quittances de loyer)
 * - Housing attestations (attestations d'hébergement)
 * - Rent attestations (attestations de loyer)
 * - Lease summary documents
 *
 * Supports i18n for fr, en, nl, de
 *
 * PERF: jsPDF (~450KB) is loaded dynamically only when generating PDFs
 * to reduce initial bundle size and improve FCP
 */

import { format } from 'date-fns';
import { fr, enUS, nl, de } from 'date-fns/locale';
// PERF: jsPDF loaded dynamically in methods that need it

// =============================================================================
// I18N CONFIGURATION
// =============================================================================
export type DocumentLanguage = 'fr' | 'en' | 'nl' | 'de';

const dateLocales = { fr, en: enUS, nl, de };
const localeMap: Record<DocumentLanguage, string> = {
  fr: 'fr-FR',
  en: 'en-GB',
  nl: 'nl-NL',
  de: 'de-DE',
};

const translations = {
  common: {
    phone: { fr: 'Tél', en: 'Tel', nl: 'Tel', de: 'Tel' },
    email: { fr: 'Email', en: 'Email', nl: 'E-mail', de: 'E-Mail' },
    on: { fr: 'Le', en: 'On', nl: 'Op', de: 'Am' },
    signature: { fr: 'Signature', en: 'Signature', nl: 'Handtekening', de: 'Unterschrift' },
    doneAt: { fr: 'Fait à', en: 'Done at', nl: 'Gedaan te', de: 'Ausgestellt in' },
    footer: {
      fr: 'Document généré par Izzico - www.izzico.app',
      en: 'Document generated by Izzico - www.izzico.app',
      nl: 'Document gegenereerd door Izzico - www.izzico.app',
      de: 'Dokument erstellt von Izzico - www.izzico.app',
    },
  },
  rentReceipt: {
    title: { fr: 'QUITTANCE DE LOYER', en: 'RENT RECEIPT', nl: 'HUURKWITANTIE', de: 'MIETQUITTUNG' },
    number: { fr: 'N°', en: 'No.', nl: 'Nr.', de: 'Nr.' },
    receivedFrom: { fr: 'Reçu de:', en: 'Received from:', nl: 'Ontvangen van:', de: 'Erhalten von:' },
    residing: { fr: 'Demeurant', en: 'Residing at', nl: 'Woonachtig te', de: 'Wohnhaft in' },
    propertyDescription: { fr: 'Désignation des locaux:', en: 'Property description:', nl: 'Beschrijving van het pand:', de: 'Objektbeschreibung:' },
    paymentDetails: { fr: 'Détail du règlement:', en: 'Payment details:', nl: 'Betalingsdetails:', de: 'Zahlungsdetails:' },
    rent: { fr: 'Loyer', en: 'Rent', nl: 'Huur', de: 'Miete' },
    charges: { fr: 'Provision pour charges', en: 'Service charges', nl: 'Voorschot servicekosten', de: 'Nebenkosten' },
    total: { fr: 'TOTAL', en: 'TOTAL', nl: 'TOTAAL', de: 'GESAMT' },
    amountInWords: { fr: 'Soit', en: 'Amount in words:', nl: 'Bedrag in woorden:', de: 'Betrag in Worten:' },
    euros: { fr: 'euros', en: 'euros', nl: 'euro', de: 'Euro' },
    cents: { fr: 'centimes', en: 'cents', nl: 'cent', de: 'Cent' },
    and: { fr: 'et', en: 'and', nl: 'en', de: 'und' },
    paymentDate: { fr: 'Date de paiement', en: 'Payment date', nl: 'Betalingsdatum', de: 'Zahlungsdatum' },
    paymentMethod: { fr: 'Mode de paiement', en: 'Payment method', nl: 'Betaalmethode', de: 'Zahlungsmethode' },
    legalNotice: {
      fr: 'Cette quittance annule tous les reçus qui auraient pu être délivrés précédemment pour le même loyer. Elle ne libère pas le locataire des loyers antérieurs ou des charges impayées.',
      en: 'This receipt cancels all receipts that may have been issued previously for the same rent. It does not release the tenant from previous rent or unpaid charges.',
      nl: 'Deze kwitantie annuleert alle eerder voor dezelfde huur afgegeven ontvangstbewijzen. Het ontslaat de huurder niet van voorgaande huur of onbetaalde kosten.',
      de: 'Diese Quittung annulliert alle zuvor für dieselbe Miete ausgestellten Quittungen. Sie entbindet den Mieter nicht von früheren Mieten oder unbezahlten Nebenkosten.',
    },
    landlordSignature: { fr: 'Signature du bailleur:', en: 'Landlord signature:', nl: 'Handtekening verhuurder:', de: 'Unterschrift Vermieter:' },
  },
  housingAttestation: {
    title: { fr: 'ATTESTATION D\'HÉBERGEMENT', en: 'HOUSING CERTIFICATE', nl: 'VERKLARING VAN HUISVESTING', de: 'WOHNBESCHEINIGUNG' },
    body: {
      fr: (hostName: string) => `Je soussigné(e), ${hostName}, atteste sur l'honneur héberger à mon domicile :`,
      en: (hostName: string) => `I, the undersigned, ${hostName}, hereby certify that I am hosting at my residence:`,
      nl: (hostName: string) => `Ondergetekende, ${hostName}, verklaart hierbij te huisvesten op mijn adres:`,
      de: (hostName: string) => `Ich, ${hostName}, erkläre hiermit, dass ich in meiner Wohnung beherberge:`,
    },
    atAddress: { fr: 'À l\'adresse suivante :', en: 'At the following address:', nl: 'Op het volgende adres:', de: 'An folgender Adresse:' },
    since: { fr: 'Depuis le', en: 'Since', nl: 'Sinds', de: 'Seit' },
    purposeDefault: {
      fr: 'Cette attestation est établie pour servir et valoir ce que de droit.',
      en: 'This certificate is issued to serve as required.',
      nl: 'Deze verklaring wordt afgegeven om te dienen waar nodig.',
      de: 'Diese Bescheinigung wird ausgestellt, um den erforderlichen Zwecken zu dienen.',
    },
    purposeCustom: {
      fr: (reason: string) => `Cette attestation est établie pour servir et valoir ce que de droit, notamment pour : ${reason}.`,
      en: (reason: string) => `This certificate is issued to serve as required, particularly for: ${reason}.`,
      nl: (reason: string) => `Deze verklaring wordt afgegeven om te dienen waar nodig, met name voor: ${reason}.`,
      de: (reason: string) => `Diese Bescheinigung wird ausgestellt, insbesondere für: ${reason}.`,
    },
    legalWarning: {
      fr: 'Attention : toute fausse attestation est passible de sanctions pénales (article 441-7 du Code pénal : un an d\'emprisonnement et 15 000 € d\'amende).',
      en: 'Warning: any false certificate is subject to criminal penalties.',
      nl: 'Waarschuwing: elke valse verklaring is strafbaar.',
      de: 'Warnung: Jede falsche Bescheinigung ist strafbar.',
    },
    closingPhrase: { fr: 'Fait pour servir et valoir ce que de droit,', en: 'Issued to serve as required,', nl: 'Afgegeven om te dienen waar nodig,', de: 'Ausgestellt zur Verwendung nach Bedarf,' },
    hostSignature: { fr: 'Signature de l\'hébergeant :', en: 'Host signature:', nl: 'Handtekening gastheer:', de: 'Unterschrift Gastgeber:' },
    readApproved: { fr: '(précédée de la mention "Lu et approuvé")', en: '(preceded by "Read and approved")', nl: '(voorafgegaan door "Gelezen en goedgekeurd")', de: '(mit dem Vermerk "Gelesen und genehmigt")' },
  },
  rentAttestation: {
    title: { fr: 'ATTESTATION DE LOYER', en: 'RENT CERTIFICATE', nl: 'HUURVERKLARING', de: 'MIETBESCHEINIGUNG' },
    iTheUndersigned: { fr: 'Je soussigné(e),', en: 'I, the undersigned,', nl: 'Ondergetekende,', de: 'Ich,' },
    propertyOwner: { fr: 'Propriétaire du logement situé :', en: 'Owner of the property located at:', nl: 'Eigenaar van het pand gelegen te:', de: 'Eigentümer der Immobilie in:' },
    certifyThat: { fr: 'Atteste que :', en: 'Certify that:', nl: 'Verklaar dat:', de: 'Bestätige, dass:' },
    isTenant: { fr: 'Est locataire de ce logement depuis le', en: 'Has been a tenant of this property since', nl: 'Is huurder van dit pand sinds', de: 'Ist Mieter dieser Immobilie seit' },
    monthlyRentIs: { fr: 'Le montant du loyer mensuel s\'élève à :', en: 'The monthly rent is:', nl: 'De maandelijkse huur bedraagt:', de: 'Die monatliche Miete beträgt:' },
    rentExcluding: { fr: 'Loyer hors charges :', en: 'Rent excluding charges:', nl: 'Huur exclusief kosten:', de: 'Miete ohne Nebenkosten:' },
    chargesProvision: { fr: 'Provision pour charges :', en: 'Service charge provision:', nl: 'Voorschot servicekosten:', de: 'Nebenkostenvorauszahlung:' },
    monthlyTotal: { fr: 'Total mensuel :', en: 'Monthly total:', nl: 'Maandelijks totaal:', de: 'Monatliche Gesamtsumme:' },
    purposeDefault: {
      fr: 'Cette attestation est établie pour servir et valoir ce que de droit.',
      en: 'This certificate is issued to serve as required.',
      nl: 'Deze verklaring wordt afgegeven om te dienen waar nodig.',
      de: 'Diese Bescheinigung wird ausgestellt, um den erforderlichen Zwecken zu dienen.',
    },
    purposeCustom: {
      fr: (purpose: string) => `Cette attestation est établie pour : ${purpose}.`,
      en: (purpose: string) => `This certificate is issued for: ${purpose}.`,
      nl: (purpose: string) => `Deze verklaring wordt afgegeven voor: ${purpose}.`,
      de: (purpose: string) => `Diese Bescheinigung wird ausgestellt für: ${purpose}.`,
    },
    closingPhrase: { fr: 'Fait pour servir et valoir ce que de droit,', en: 'Issued to serve as required,', nl: 'Afgegeven om te dienen waar nodig,', de: 'Ausgestellt zur Verwendung nach Bedarf,' },
    ownerSignature: { fr: 'Signature du propriétaire :', en: 'Owner signature:', nl: 'Handtekening eigenaar:', de: 'Unterschrift Eigentümer:' },
  },
  filenameLabels: {
    receipt: { fr: 'quittance', en: 'receipt', nl: 'kwitantie', de: 'quittung' },
    housing: { fr: 'hebergement', en: 'housing', nl: 'huisvesting', de: 'wohnung' },
    rent: { fr: 'loyer', en: 'rent', nl: 'huur', de: 'miete' },
    attestation: { fr: 'attestation', en: 'certificate', nl: 'verklaring', de: 'bescheinigung' },
  },
};

// Types
export interface TenantInfo {
  firstName: string;
  lastName: string;
  email: string;
  phone?: string;
}

export interface PropertyInfo {
  title: string;
  address: string;
  city: string;
  postalCode: string;
  type?: string;
}

export interface OwnerInfo {
  name: string;
  address?: string;
  phone?: string;
  email?: string;
}

export interface RentReceiptData {
  tenant: TenantInfo;
  property: PropertyInfo;
  owner: OwnerInfo;
  period: {
    month: number; // 1-12
    year: number;
  };
  amounts: {
    rent: number;
    charges: number;
    total: number;
  };
  paymentDate: Date;
  paymentMethod?: string;
  receiptNumber?: string;
}

export interface HousingAttestationData {
  host: OwnerInfo;
  guest: TenantInfo;
  property: PropertyInfo;
  startDate: Date;
  reason?: string;
}

export interface RentAttestationData {
  tenant: TenantInfo;
  property: PropertyInfo;
  owner: OwnerInfo;
  monthlyRent: number;
  chargesAmount: number;
  leaseStartDate: Date;
  purpose?: string;
}

export interface LeaseDocumentData {
  tenant: TenantInfo;
  property: PropertyInfo;
  owner: OwnerInfo;
  lease: {
    startDate: Date;
    durationMonths: number;
    monthlyRent: number;
    depositAmount: number;
    chargesAmount?: number;
  };
}

// =============================================================================
// HELPER FUNCTIONS
// =============================================================================

const formatCurrency = (amount: number, language: DocumentLanguage = 'fr'): string =>
  new Intl.NumberFormat(localeMap[language], { style: 'currency', currency: 'EUR' }).format(amount);

const formatDate = (date: Date, language: DocumentLanguage = 'fr'): string =>
  format(date, "d MMMM yyyy", { locale: dateLocales[language] });

const formatMonth = (month: number, year: number, language: DocumentLanguage = 'fr'): string => {
  const date = new Date(year, month - 1, 1);
  return format(date, "MMMM yyyy", { locale: dateLocales[language] });
};

// Number to words functions for each language
const numberToWordsFr = (n: number): string => {
  const units = ['', 'un', 'deux', 'trois', 'quatre', 'cinq', 'six', 'sept', 'huit', 'neuf', 'dix', 'onze', 'douze', 'treize', 'quatorze', 'quinze', 'seize', 'dix-sept', 'dix-huit', 'dix-neuf'];
  const tens = ['', '', 'vingt', 'trente', 'quarante', 'cinquante', 'soixante', 'soixante', 'quatre-vingt', 'quatre-vingt'];

  if (n === 0) return 'zéro';
  if (n < 0) return `moins ${numberToWordsFr(-n)}`;
  if (n < 20) return units[n];
  if (n < 100) {
    const t = Math.floor(n / 10);
    const u = n % 10;
    if (t === 7 || t === 9) return `${tens[t]}-${units[10 + u]}`;
    return u === 0 ? tens[t] : `${tens[t]}-${units[u]}`;
  }
  if (n < 1000) {
    const h = Math.floor(n / 100);
    const remainder = n % 100;
    const prefix = h === 1 ? 'cent' : `${units[h]} cent`;
    return remainder === 0 ? prefix : `${prefix} ${numberToWordsFr(remainder)}`;
  }
  if (n < 1000000) {
    const thousands = Math.floor(n / 1000);
    const remainder = n % 1000;
    const prefix = thousands === 1 ? 'mille' : `${numberToWordsFr(thousands)} mille`;
    return remainder === 0 ? prefix : `${prefix} ${numberToWordsFr(remainder)}`;
  }
  return n.toString();
};

const numberToWordsEn = (n: number): string => {
  const units = ['', 'one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine', 'ten', 'eleven', 'twelve', 'thirteen', 'fourteen', 'fifteen', 'sixteen', 'seventeen', 'eighteen', 'nineteen'];
  const tens = ['', '', 'twenty', 'thirty', 'forty', 'fifty', 'sixty', 'seventy', 'eighty', 'ninety'];

  if (n === 0) return 'zero';
  if (n < 0) return `minus ${numberToWordsEn(-n)}`;
  if (n < 20) return units[n];
  if (n < 100) {
    const t = Math.floor(n / 10);
    const u = n % 10;
    return u === 0 ? tens[t] : `${tens[t]}-${units[u]}`;
  }
  if (n < 1000) {
    const h = Math.floor(n / 100);
    const remainder = n % 100;
    return remainder === 0 ? `${units[h]} hundred` : `${units[h]} hundred and ${numberToWordsEn(remainder)}`;
  }
  if (n < 1000000) {
    const thousands = Math.floor(n / 1000);
    const remainder = n % 1000;
    return remainder === 0 ? `${numberToWordsEn(thousands)} thousand` : `${numberToWordsEn(thousands)} thousand ${numberToWordsEn(remainder)}`;
  }
  return n.toString();
};

const numberToWordsNl = (n: number): string => {
  const units = ['', 'een', 'twee', 'drie', 'vier', 'vijf', 'zes', 'zeven', 'acht', 'negen', 'tien', 'elf', 'twaalf', 'dertien', 'veertien', 'vijftien', 'zestien', 'zeventien', 'achttien', 'negentien'];
  const tens = ['', '', 'twintig', 'dertig', 'veertig', 'vijftig', 'zestig', 'zeventig', 'tachtig', 'negentig'];

  if (n === 0) return 'nul';
  if (n < 0) return `min ${numberToWordsNl(-n)}`;
  if (n < 20) return units[n];
  if (n < 100) {
    const t = Math.floor(n / 10);
    const u = n % 10;
    return u === 0 ? tens[t] : `${units[u]}en${tens[t]}`;
  }
  if (n < 1000) {
    const h = Math.floor(n / 100);
    const remainder = n % 100;
    const prefix = h === 1 ? 'honderd' : `${units[h]}honderd`;
    return remainder === 0 ? prefix : `${prefix}${numberToWordsNl(remainder)}`;
  }
  if (n < 1000000) {
    const thousands = Math.floor(n / 1000);
    const remainder = n % 1000;
    const prefix = thousands === 1 ? 'duizend' : `${numberToWordsNl(thousands)}duizend`;
    return remainder === 0 ? prefix : `${prefix} ${numberToWordsNl(remainder)}`;
  }
  return n.toString();
};

const numberToWordsDe = (n: number): string => {
  const units = ['', 'eins', 'zwei', 'drei', 'vier', 'fünf', 'sechs', 'sieben', 'acht', 'neun', 'zehn', 'elf', 'zwölf', 'dreizehn', 'vierzehn', 'fünfzehn', 'sechzehn', 'siebzehn', 'achtzehn', 'neunzehn'];
  const tens = ['', '', 'zwanzig', 'dreißig', 'vierzig', 'fünfzig', 'sechzig', 'siebzig', 'achtzig', 'neunzig'];

  if (n === 0) return 'null';
  if (n < 0) return `minus ${numberToWordsDe(-n)}`;
  if (n < 20) return units[n];
  if (n < 100) {
    const t = Math.floor(n / 10);
    const u = n % 10;
    return u === 0 ? tens[t] : `${units[u]}und${tens[t]}`;
  }
  if (n < 1000) {
    const h = Math.floor(n / 100);
    const remainder = n % 100;
    const prefix = `${units[h]}hundert`;
    return remainder === 0 ? prefix : `${prefix}${numberToWordsDe(remainder)}`;
  }
  if (n < 1000000) {
    const thousands = Math.floor(n / 1000);
    const remainder = n % 1000;
    const prefix = thousands === 1 ? 'eintausend' : `${numberToWordsDe(thousands)}tausend`;
    return remainder === 0 ? prefix : `${prefix} ${numberToWordsDe(remainder)}`;
  }
  return n.toString();
};

const numberToWords = (n: number, language: DocumentLanguage = 'fr'): string => {
  switch (language) {
    case 'en': return numberToWordsEn(n);
    case 'nl': return numberToWordsNl(n);
    case 'de': return numberToWordsDe(n);
    default: return numberToWordsFr(n);
  }
};

class DocumentGenerationService {
  /**
   * Generate a rent receipt (quittance de loyer) PDF
   * PERF: jsPDF loaded dynamically only when generating PDFs
   */
  async generateRentReceipt(data: RentReceiptData, language: DocumentLanguage = 'fr'): Promise<Blob> {
    // PERF: Dynamic import - jsPDF (~450KB) only loaded when generating PDF
    const { default: jsPDF } = await import('jspdf');

    const t = translations.rentReceipt;
    const tc = translations.common;
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 20;
    let y = 20;

    // Header with owner info
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.text(data.owner.name, margin, y);
    y += 6;

    doc.setFont('helvetica', 'normal');
    if (data.owner.address) {
      doc.text(data.owner.address, margin, y);
      y += 5;
    }
    if (data.owner.phone) {
      doc.text(`${tc.phone[language]}: ${data.owner.phone}`, margin, y);
      y += 5;
    }
    if (data.owner.email) {
      doc.text(`${tc.email[language]}: ${data.owner.email}`, margin, y);
      y += 5;
    }

    // Receipt number and date (right aligned)
    const receiptDate = formatDate(new Date(), language);
    const receiptNumber = data.receiptNumber || `QT-${data.period.year}${String(data.period.month).padStart(2, '0')}-${Date.now().toString().slice(-6)}`;
    doc.text(`${t.number[language]} ${receiptNumber}`, pageWidth - margin, 20, { align: 'right' });
    doc.text(`${tc.on[language]} ${receiptDate}`, pageWidth - margin, 26, { align: 'right' });

    // Title
    y = 55;
    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    doc.text(t.title[language], pageWidth / 2, y, { align: 'center' });

    y += 8;
    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    doc.text(formatMonth(data.period.month, data.period.year, language).toUpperCase(), pageWidth / 2, y, { align: 'center' });

    // Tenant info
    y += 20;
    doc.setFontSize(11);
    doc.text(t.receivedFrom[language], margin, y);
    y += 7;
    doc.setFont('helvetica', 'bold');
    doc.text(`${data.tenant.firstName} ${data.tenant.lastName}`, margin, y);
    y += 6;
    doc.setFont('helvetica', 'normal');
    doc.text(`${t.residing[language]}: ${data.property.address}`, margin, y);
    y += 5;
    doc.text(`${data.property.postalCode} ${data.property.city}`, margin, y);

    // Property description
    y += 15;
    doc.setFont('helvetica', 'bold');
    doc.text(t.propertyDescription[language], margin, y);
    y += 7;
    doc.setFont('helvetica', 'normal');
    doc.text(`${data.property.title}`, margin, y);
    y += 5;
    doc.text(`${data.property.address}, ${data.property.postalCode} ${data.property.city}`, margin, y);

    // Payment details
    y += 20;
    doc.setFont('helvetica', 'bold');
    doc.text(t.paymentDetails[language], margin, y);
    y += 10;

    // Table header
    const col1 = margin;
    const col2 = 140;

    doc.setFont('helvetica', 'normal');
    doc.text(t.rent[language], col1, y);
    doc.text(formatCurrency(data.amounts.rent, language), col2, y);
    y += 7;

    doc.text(t.charges[language], col1, y);
    doc.text(formatCurrency(data.amounts.charges, language), col2, y);
    y += 7;

    // Separator line
    doc.setLineWidth(0.5);
    doc.line(col1, y, col2 + 30, y);
    y += 7;

    // Total
    doc.setFont('helvetica', 'bold');
    doc.text(t.total[language], col1, y);
    doc.text(formatCurrency(data.amounts.total, language), col2, y);
    y += 5;

    // Amount in words
    y += 5;
    doc.setFontSize(10);
    doc.setFont('helvetica', 'italic');
    const cents = Math.round((data.amounts.total % 1) * 100);
    const euros = Math.floor(data.amounts.total);
    let amountWords = `${t.amountInWords[language]} ${numberToWords(euros, language)} ${t.euros[language]}`;
    if (cents > 0) {
      amountWords += ` ${t.and[language]} ${numberToWords(cents, language)} ${t.cents[language]}`;
    }
    doc.text(amountWords, margin, y);

    // Payment info
    y += 15;
    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    doc.text(`${t.paymentDate[language]}: ${formatDate(data.paymentDate, language)}`, margin, y);
    if (data.paymentMethod) {
      y += 6;
      doc.text(`${t.paymentMethod[language]}: ${data.paymentMethod}`, margin, y);
    }

    // Legal mention
    y += 20;
    doc.setFontSize(10);
    doc.setTextColor(100);
    const legalText = t.legalNotice[language];
    const splitLegal = doc.splitTextToSize(legalText, pageWidth - (2 * margin));
    doc.text(splitLegal, margin, y);

    // Signature
    y += 30;
    doc.setTextColor(0);
    doc.setFontSize(11);
    doc.text(`${tc.doneAt[language]} ___________________`, margin, y);
    doc.text(`${tc.on[language]} ${receiptDate}`, margin + 80, y);
    y += 15;
    doc.text(t.landlordSignature[language], margin, y);

    // Footer
    y = doc.internal.pageSize.getHeight() - 15;
    doc.setFontSize(8);
    doc.setTextColor(128);
    doc.text(tc.footer[language], pageWidth / 2, y, { align: 'center' });

    return doc.output('blob');
  }

  /**
   * Generate a housing attestation (attestation d'hébergement) PDF
   * PERF: jsPDF loaded dynamically only when generating PDFs
   */
  async generateHousingAttestation(data: HousingAttestationData, language: DocumentLanguage = 'fr'): Promise<Blob> {
    // PERF: Dynamic import - jsPDF (~450KB) only loaded when generating PDF
    const { default: jsPDF } = await import('jspdf');

    const t = translations.housingAttestation;
    const tc = translations.common;
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 20;
    let y = 20;

    // Header
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.text(data.host.name, margin, y);
    y += 6;

    doc.setFont('helvetica', 'normal');
    if (data.host.address) {
      doc.text(data.host.address, margin, y);
      y += 5;
    }

    // Date (right aligned)
    const currentDate = formatDate(new Date(), language);
    doc.text(`${tc.on[language]} ${currentDate}`, pageWidth - margin, 20, { align: 'right' });

    // Title
    y = 55;
    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    doc.text(t.title[language], pageWidth / 2, y, { align: 'center' });

    // Body
    y += 25;
    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');

    const bodyText = t.body[language](data.host.name);
    doc.text(bodyText, margin, y);

    y += 15;
    doc.setFont('helvetica', 'bold');
    doc.text(`${data.guest.firstName} ${data.guest.lastName}`, margin + 20, y);

    y += 15;
    doc.setFont('helvetica', 'normal');
    doc.text(t.atAddress[language], margin, y);

    y += 8;
    doc.setFont('helvetica', 'bold');
    doc.text(`${data.property.address}`, margin + 20, y);
    y += 6;
    doc.text(`${data.property.postalCode} ${data.property.city}`, margin + 20, y);

    y += 15;
    doc.setFont('helvetica', 'normal');
    doc.text(`${t.since[language]} ${formatDate(data.startDate, language)}.`, margin, y);

    if (data.reason) {
      y += 10;
      const reasonText = t.purposeCustom[language](data.reason);
      const splitReason = doc.splitTextToSize(reasonText, pageWidth - (2 * margin));
      doc.text(splitReason, margin, y);
      y += splitReason.length * 6;
    } else {
      y += 10;
      doc.text(t.purposeDefault[language], margin, y);
    }

    // Legal warning
    y += 25;
    doc.setFontSize(9);
    doc.setTextColor(100);
    const warningText = t.legalWarning[language];
    const splitWarning = doc.splitTextToSize(warningText, pageWidth - (2 * margin));
    doc.text(splitWarning, margin, y);

    // Signature
    y += 25;
    doc.setTextColor(0);
    doc.setFontSize(11);
    doc.text(t.closingPhrase[language], margin, y);
    y += 20;
    doc.text(t.hostSignature[language], margin, y);
    y += 5;
    doc.text(t.readApproved[language], margin, y);

    // Footer
    y = doc.internal.pageSize.getHeight() - 15;
    doc.setFontSize(8);
    doc.setTextColor(128);
    doc.text(tc.footer[language], pageWidth / 2, y, { align: 'center' });

    return doc.output('blob');
  }

  /**
   * Generate a rent attestation (attestation de loyer) PDF
   * PERF: jsPDF loaded dynamically only when generating PDFs
   */
  async generateRentAttestation(data: RentAttestationData, language: DocumentLanguage = 'fr'): Promise<Blob> {
    // PERF: Dynamic import - jsPDF (~450KB) only loaded when generating PDF
    const { default: jsPDF } = await import('jspdf');

    const t = translations.rentAttestation;
    const tc = translations.common;
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 20;
    let y = 20;

    // Owner header
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.text(data.owner.name, margin, y);
    y += 6;

    doc.setFont('helvetica', 'normal');
    if (data.owner.address) {
      doc.text(data.owner.address, margin, y);
      y += 5;
    }
    if (data.owner.phone) {
      doc.text(`${tc.phone[language]}: ${data.owner.phone}`, margin, y);
      y += 5;
    }

    // Date (right aligned)
    const currentDate = formatDate(new Date(), language);
    doc.text(`${tc.on[language]} ${currentDate}`, pageWidth - margin, 20, { align: 'right' });

    // Title
    y = 55;
    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    doc.text(t.title[language], pageWidth / 2, y, { align: 'center' });

    // Body
    y += 25;
    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');

    doc.text(t.iTheUndersigned[language], margin, y);
    y += 8;
    doc.setFont('helvetica', 'bold');
    doc.text(data.owner.name, margin + 20, y);
    y += 8;
    doc.setFont('helvetica', 'normal');
    doc.text(t.propertyOwner[language], margin, y);
    y += 8;
    doc.setFont('helvetica', 'bold');
    doc.text(`${data.property.address}`, margin + 20, y);
    y += 6;
    doc.text(`${data.property.postalCode} ${data.property.city}`, margin + 20, y);

    y += 15;
    doc.setFont('helvetica', 'normal');
    doc.text(t.certifyThat[language], margin, y);

    y += 12;
    doc.setFont('helvetica', 'bold');
    doc.text(`${data.tenant.firstName} ${data.tenant.lastName}`, margin + 20, y);

    y += 10;
    doc.setFont('helvetica', 'normal');
    doc.text(`${t.isTenant[language]} ${formatDate(data.leaseStartDate, language)}.`, margin, y);

    // Rent details
    y += 15;
    doc.text(t.monthlyRentIs[language], margin, y);
    y += 10;

    const col1 = margin + 20;
    const col2 = 140;

    doc.text(t.rentExcluding[language], col1, y);
    doc.setFont('helvetica', 'bold');
    doc.text(formatCurrency(data.monthlyRent, language), col2, y);
    y += 7;

    doc.setFont('helvetica', 'normal');
    doc.text(t.chargesProvision[language], col1, y);
    doc.setFont('helvetica', 'bold');
    doc.text(formatCurrency(data.chargesAmount, language), col2, y);
    y += 7;

    doc.setLineWidth(0.3);
    doc.line(col1, y, col2 + 30, y);
    y += 7;

    doc.setFont('helvetica', 'normal');
    doc.text(t.monthlyTotal[language], col1, y);
    doc.setFont('helvetica', 'bold');
    doc.text(formatCurrency(data.monthlyRent + data.chargesAmount, language), col2, y);

    // Purpose
    y += 20;
    doc.setFont('helvetica', 'normal');
    if (data.purpose) {
      doc.text(t.purposeCustom[language](data.purpose), margin, y);
    } else {
      doc.text(t.purposeDefault[language], margin, y);
    }

    // Signature
    y += 30;
    doc.text(t.closingPhrase[language], margin, y);
    y += 20;
    doc.text(t.ownerSignature[language], margin, y);

    // Footer
    y = doc.internal.pageSize.getHeight() - 15;
    doc.setFontSize(8);
    doc.setTextColor(128);
    doc.text(tc.footer[language], pageWidth / 2, y, { align: 'center' });

    return doc.output('blob');
  }

  /**
   * Download a document as a file
   */
  downloadDocument(blob: Blob, filename: string): void {
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  }

  /**
   * Generate rent receipt filename
   */
  generateReceiptFilename(tenantName: string, month: number, year: number, language: DocumentLanguage = 'fr'): string {
    const monthStr = String(month).padStart(2, '0');
    const sanitizedName = tenantName.replace(/[^a-zA-Z0-9]/g, '_');
    const label = translations.filenameLabels.receipt[language];
    return `${label}_${sanitizedName}_${year}_${monthStr}.pdf`;
  }

  /**
   * Generate attestation filename
   */
  generateAttestationFilename(type: 'housing' | 'rent', tenantName: string, language: DocumentLanguage = 'fr'): string {
    const sanitizedName = tenantName.replace(/[^a-zA-Z0-9]/g, '_');
    const date = format(new Date(), 'yyyy-MM-dd');
    const typeLabel = type === 'housing'
      ? translations.filenameLabels.housing[language]
      : translations.filenameLabels.rent[language];
    const attestationLabel = translations.filenameLabels.attestation[language];
    return `${attestationLabel}_${typeLabel}_${sanitizedName}_${date}.pdf`;
  }
}

export const documentGenerationService = new DocumentGenerationService();
