/**
 * Export Service
 * Handles CSV and PDF export functionality for finance and other data
 * Supports i18n for fr, en, nl, de languages
 */

// =============================================================================
// TRANSLATIONS
// =============================================================================
export type ExportLanguage = 'fr' | 'en' | 'nl' | 'de';

const translations = {
  status: {
    paid: { fr: 'Payé', en: 'Paid', nl: 'Betaald', de: 'Bezahlt' },
    pending: { fr: 'En attente', en: 'Pending', nl: 'In afwachting', de: 'Ausstehend' },
    overdue: { fr: 'En retard', en: 'Overdue', nl: 'Te laat', de: 'Überfällig' },
  },
  csv: {
    date: { fr: 'Date', en: 'Date', nl: 'Datum', de: 'Datum' },
    tenant: { fr: 'Locataire', en: 'Tenant', nl: 'Huurder', de: 'Mieter' },
    property: { fr: 'Propriété', en: 'Property', nl: 'Eigendom', de: 'Immobilie' },
    amount: { fr: 'Montant', en: 'Amount', nl: 'Bedrag', de: 'Betrag' },
    status: { fr: 'Statut', en: 'Status', nl: 'Status', de: 'Status' },
    method: { fr: 'Méthode', en: 'Method', nl: 'Methode', de: 'Methode' },
    total: { fr: 'TOTAL', en: 'TOTAL', nl: 'TOTAAL', de: 'GESAMT' },
    rate: { fr: 'Taux', en: 'Rate', nl: 'Tarief', de: 'Rate' },
  },
  pdf: {
    title: { fr: 'Rapport Financier', en: 'Financial Report', nl: 'Financieel Rapport', de: 'Finanzbericht' },
    generatedOn: { fr: 'Généré le', en: 'Generated on', nl: 'Gegenereerd op', de: 'Erstellt am' },
    at: { fr: 'à', en: 'at', nl: 'om', de: 'um' },
    collected: { fr: 'Encaissé', en: 'Collected', nl: 'Geïnd', de: 'Eingezogen' },
    expected: { fr: 'Attendu', en: 'Expected', nl: 'Verwacht', de: 'Erwartet' },
    overdue: { fr: 'Impayés', en: 'Overdue', nl: 'Achterstallig', de: 'Überfällig' },
    rate: { fr: 'Taux', en: 'Rate', nl: 'Tarief', de: 'Rate' },
    paymentDetails: { fr: 'Détail des paiements', en: 'Payment Details', nl: 'Betalingsdetails', de: 'Zahlungsdetails' },
    footer: {
      fr: 'Document généré automatiquement par Izzico - Ce document n\'a pas de valeur légale',
      en: 'Document automatically generated by Izzico - This document has no legal value',
      nl: 'Document automatisch gegenereerd door Izzico - Dit document heeft geen juridische waarde',
      de: 'Dokument automatisch erstellt von Izzico - Dieses Dokument hat keinen rechtlichen Wert',
    },
  },
};

// Locale mapping for date/number formatting
const localeMap: Record<ExportLanguage, string> = {
  fr: 'fr-FR',
  en: 'en-GB',
  nl: 'nl-NL',
  de: 'de-DE',
};

// CSV delimiter varies by locale (semicolon for FR/DE, comma for EN/NL)
const csvDelimiter: Record<ExportLanguage, string> = {
  fr: ';',
  en: ',',
  nl: ';',
  de: ';',
};

// Decimal separator varies by locale
const decimalSeparator: Record<ExportLanguage, string> = {
  fr: ',',
  en: '.',
  nl: ',',
  de: ',',
};

// =============================================================================
// CSV EXPORT
// =============================================================================

// CSV Export with BOM for Excel compatibility
export function exportToCSV(
  data: Record<string, unknown>[],
  filename: string,
  headers?: string[],
  language: ExportLanguage = 'fr'
): void {
  if (data.length === 0) {
    console.warn('No data to export');
    return;
  }

  const keys = headers || Object.keys(data[0]);
  const delimiter = csvDelimiter[language];
  const decimal = decimalSeparator[language];

  // Create CSV content with BOM for Excel
  const BOM = '\uFEFF';
  const csvContent = [
    keys.join(delimiter), // Header row with locale-appropriate delimiter
    ...data.map(row =>
      keys.map(key => {
        const value = row[key];
        // Handle different types and escape quotes
        if (value === null || value === undefined) return '';
        if (typeof value === 'string') return `"${value.replace(/"/g, '""')}"`;
        if (typeof value === 'number') return value.toString().replace('.', decimal);
        return String(value);
      }).join(delimiter)
    )
  ].join('\n');

  // Create and download file
  const blob = new Blob([BOM + csvContent], { type: 'text/csv;charset=utf-8;' });
  downloadBlob(blob, `${filename}.csv`);
}

// Finance-specific CSV export
export interface FinanceExportData {
  payments: PaymentExportRecord[];
  summary: {
    totalCollected: number;
    totalExpected: number;
    totalOverdue: number;
    collectionRate: number;
  };
  period: string;
}

export interface PaymentExportRecord {
  date: string;
  tenant: string;
  property: string;
  amount: number;
  status: 'paid' | 'pending' | 'overdue';
  paymentMethod?: string;
}

export function exportFinanceToCSV(data: FinanceExportData, language: ExportLanguage = 'fr'): void {
  const t = translations;
  const headers = [
    t.csv.date[language],
    t.csv.tenant[language],
    t.csv.property[language],
    t.csv.amount[language],
    t.csv.status[language],
    t.csv.method[language],
  ];

  const csvData = data.payments.map(p => ({
    [t.csv.date[language]]: p.date,
    [t.csv.tenant[language]]: p.tenant,
    [t.csv.property[language]]: p.property,
    [t.csv.amount[language]]: p.amount,
    [t.csv.status[language]]: t.status[p.status][language],
    [t.csv.method[language]]: p.paymentMethod || '-'
  }));

  // Add summary row
  csvData.push({
    [t.csv.date[language]]: '',
    [t.csv.tenant[language]]: '',
    [t.csv.property[language]]: t.csv.total[language],
    [t.csv.amount[language]]: data.summary.totalCollected,
    [t.csv.status[language]]: `${t.csv.rate[language]}: ${data.summary.collectionRate}%`,
    [t.csv.method[language]]: ''
  });

  exportToCSV(csvData, `finances-${data.period}`, headers, language);
}

// PDF Export using iframe + srcdoc (secure approach)
export function exportFinanceToPDF(data: FinanceExportData, language: ExportLanguage = 'fr'): void {
  const html = generateFinancePDFHTML(data, language);

  // Create hidden iframe for printing
  const iframe = document.createElement('iframe');
  iframe.style.position = 'fixed';
  iframe.style.right = '0';
  iframe.style.bottom = '0';
  iframe.style.width = '0';
  iframe.style.height = '0';
  iframe.style.border = 'none';

  document.body.appendChild(iframe);

  // Use srcdoc attribute (safer than document.write)
  iframe.srcdoc = html;

  // Wait for content to load then print
  iframe.onload = () => {
    setTimeout(() => {
      iframe.contentWindow?.print();
      // Clean up after print dialog closes
      setTimeout(() => {
        document.body.removeChild(iframe);
      }, 1000);
    }, 250);
  };
}

function generateFinancePDFHTML(data: FinanceExportData, language: ExportLanguage = 'fr'): string {
  const t = translations;
  const locale = localeMap[language];

  const statusColors: Record<string, string> = {
    paid: '#10b981',
    pending: '#f59e0b',
    overdue: '#ef4444'
  };

  const paymentsRows = data.payments.map(p => `
    <tr>
      <td>${escapeHtml(p.date)}</td>
      <td>${escapeHtml(p.tenant)}</td>
      <td>${escapeHtml(p.property)}</td>
      <td class="amount">${formatCurrency(p.amount, language)}</td>
      <td><span class="status" style="background: ${statusColors[p.status]}20; color: ${statusColors[p.status]}">${t.status[p.status][language]}</span></td>
    </tr>
  `).join('');

  return `
<!DOCTYPE html>
<html lang="${language}">
<head>
  <meta charset="UTF-8">
  <title>${t.pdf.title[language]} - ${escapeHtml(data.period)}</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      color: #1f2937;
      padding: 40px;
      max-width: 800px;
      margin: 0 auto;
    }
    .header {
      display: flex;
      justify-content: space-between;
      align-items: flex-start;
      margin-bottom: 30px;
      padding-bottom: 20px;
      border-bottom: 2px solid #9c5698;
    }
    .logo {
      font-size: 24px;
      font-weight: 700;
      background: linear-gradient(135deg, #9c5698, #c2566b);
      -webkit-background-clip: text;
      -webkit-text-fill-color: transparent;
      background-clip: text;
    }
    .period {
      font-size: 14px;
      color: #6b7280;
    }
    .summary {
      display: grid;
      grid-template-columns: repeat(4, 1fr);
      gap: 16px;
      margin-bottom: 30px;
    }
    .summary-card {
      background: #f9fafb;
      border-radius: 12px;
      padding: 16px;
      text-align: center;
    }
    .summary-card .label {
      font-size: 12px;
      color: #6b7280;
      margin-bottom: 4px;
    }
    .summary-card .value {
      font-size: 20px;
      font-weight: 700;
      color: #1f2937;
    }
    .summary-card.highlight {
      background: linear-gradient(135deg, #9c5698, #c2566b);
    }
    .summary-card.highlight .label,
    .summary-card.highlight .value {
      color: white;
    }
    h2 {
      font-size: 16px;
      font-weight: 600;
      margin-bottom: 16px;
      color: #374151;
    }
    table {
      width: 100%;
      border-collapse: collapse;
      font-size: 13px;
    }
    th {
      background: #f3f4f6;
      padding: 12px 8px;
      text-align: left;
      font-weight: 600;
      color: #374151;
      border-bottom: 1px solid #e5e7eb;
    }
    td {
      padding: 12px 8px;
      border-bottom: 1px solid #f3f4f6;
    }
    .amount {
      font-weight: 600;
      text-align: right;
    }
    .status {
      display: inline-block;
      padding: 4px 8px;
      border-radius: 6px;
      font-size: 11px;
      font-weight: 500;
    }
    .footer {
      margin-top: 40px;
      padding-top: 20px;
      border-top: 1px solid #e5e7eb;
      font-size: 11px;
      color: #9ca3af;
      text-align: center;
    }
    @media print {
      body { padding: 20px; }
      .summary-card.highlight {
        background: #9c5698 !important;
        -webkit-print-color-adjust: exact;
        print-color-adjust: exact;
      }
    }
  </style>
</head>
<body>
  <div class="header">
    <div>
      <div class="logo">Izzico</div>
      <div class="period">${t.pdf.title[language]} - ${escapeHtml(data.period)}</div>
    </div>
    <div style="text-align: right; font-size: 12px; color: #6b7280;">
      ${t.pdf.generatedOn[language]} ${new Date().toLocaleDateString(locale)}<br>
      ${t.pdf.at[language]} ${new Date().toLocaleTimeString(locale, { hour: '2-digit', minute: '2-digit' })}
    </div>
  </div>

  <div class="summary">
    <div class="summary-card highlight">
      <div class="label">${t.pdf.collected[language]}</div>
      <div class="value">${formatCurrency(data.summary.totalCollected, language)}</div>
    </div>
    <div class="summary-card">
      <div class="label">${t.pdf.expected[language]}</div>
      <div class="value">${formatCurrency(data.summary.totalExpected, language)}</div>
    </div>
    <div class="summary-card">
      <div class="label">${t.pdf.overdue[language]}</div>
      <div class="value" style="color: #ef4444">${formatCurrency(data.summary.totalOverdue, language)}</div>
    </div>
    <div class="summary-card">
      <div class="label">${t.pdf.rate[language]}</div>
      <div class="value">${data.summary.collectionRate}%</div>
    </div>
  </div>

  <h2>${t.pdf.paymentDetails[language]}</h2>
  <table>
    <thead>
      <tr>
        <th>${t.csv.date[language]}</th>
        <th>${t.csv.tenant[language]}</th>
        <th>${t.csv.property[language]}</th>
        <th style="text-align: right">${t.csv.amount[language]}</th>
        <th>${t.csv.status[language]}</th>
      </tr>
    </thead>
    <tbody>
      ${paymentsRows}
    </tbody>
  </table>

  <div class="footer">
    ${t.pdf.footer[language]}
  </div>
</body>
</html>
  `;
}

// Utility functions
function downloadBlob(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

function formatCurrency(amount: number, language: ExportLanguage = 'fr'): string {
  return new Intl.NumberFormat(localeMap[language], {
    style: 'currency',
    currency: 'EUR',
    minimumFractionDigits: 0,
    maximumFractionDigits: 0
  }).format(amount);
}

function escapeHtml(str: string): string {
  const div = document.createElement('div');
  div.textContent = str;
  return div.innerHTML;
}
