/**
 * Mock Events Data for Development
 * Diverse range of activities to showcase the Events feature
 */

import { Event, EventCategory } from '@/lib/types/events';

// ============================================================================
// CATEGORIES
// ============================================================================

export const MOCK_CATEGORIES: EventCategory[] = [
  {
    id: 'cat-1',
    slug: 'festivals',
    name_fr: 'Festivals & Concerts',
    name_en: 'Festivals & Concerts',
    icon_name: 'Music',
    color: '#e05747',
    display_order: 1,
    created_at: new Date().toISOString(),
  },
  {
    id: 'cat-2',
    slug: 'museums',
    name_fr: 'Musées & Expos',
    name_en: 'Museums & Exhibitions',
    icon_name: 'Palette',
    color: '#9c5698',
    display_order: 2,
    created_at: new Date().toISOString(),
  },
  {
    id: 'cat-3',
    slug: 'sports',
    name_fr: 'Sport & Fitness',
    name_en: 'Sports & Fitness',
    icon_name: 'Dumbbell',
    color: '#ffa000',
    display_order: 3,
    created_at: new Date().toISOString(),
  },
  {
    id: 'cat-4',
    slug: 'nightlife',
    name_fr: 'Soirées & Bars',
    name_en: 'Nightlife & Bars',
    icon_name: 'PartyPopper',
    color: '#d15659',
    display_order: 4,
    created_at: new Date().toISOString(),
  },
  {
    id: 'cat-5',
    slug: 'food',
    name_fr: 'Food & Restaurants',
    name_en: 'Food & Restaurants',
    icon_name: 'UtensilsCrossed',
    color: '#ff7c10',
    display_order: 5,
    created_at: new Date().toISOString(),
  },
  {
    id: 'cat-6',
    slug: 'gaming',
    name_fr: 'Escape Room & Gaming',
    name_en: 'Escape Room & Gaming',
    icon_name: 'Gamepad2',
    color: '#c85570',
    display_order: 6,
    created_at: new Date().toISOString(),
  },
  {
    id: 'cat-7',
    slug: 'outdoor',
    name_fr: 'Activités Outdoor',
    name_en: 'Outdoor Activities',
    icon_name: 'TreePine',
    color: '#7CB89B',
    display_order: 7,
    created_at: new Date().toISOString(),
  },
  {
    id: 'cat-8',
    slug: 'culture',
    name_fr: 'Théâtre & Cinéma',
    name_en: 'Theater & Cinema',
    icon_name: 'Theater',
    color: '#9c5698',
    display_order: 8,
    created_at: new Date().toISOString(),
  },
  {
    id: 'cat-9',
    slug: 'wellness',
    name_fr: 'Bien-être & Détente',
    name_en: 'Wellness & Relaxation',
    icon_name: 'Sparkles',
    color: '#D08080',
    display_order: 9,
    created_at: new Date().toISOString(),
  },
  {
    id: 'cat-10',
    slug: 'networking',
    name_fr: 'Networking & Business',
    name_en: 'Networking & Business',
    icon_name: 'Users',
    color: '#1A1A2E',
    display_order: 10,
    created_at: new Date().toISOString(),
  },
];

// ============================================================================
// EVENTS - Diverse mock data
// ============================================================================

export const MOCK_EVENTS: Event[] = [
  // 1. FREE FESTIVAL - Public Event
  {
    id: 'evt-1',
    event_type: 'public',
    title: 'Brussels Jazz Marathon 2026',
    description:
      "Le plus grand festival de jazz gratuit d'Europe revient pour une 10ème édition ! Plus de 500 concerts dans 100 lieux différents à travers Bruxelles. Découvre du jazz classique, moderne, fusion et bien plus encore. Des artistes internationaux et locaux se produiront dans des bars, clubs, musées et même dans la rue !",
    short_description: '500 concerts gratuits dans toute la ville 🎷',
    category_id: 'cat-1',
    category: MOCK_CATEGORIES[0],
    city: 'Bruxelles',
    venue_name: 'Centre-ville de Bruxelles',
    venue_address: 'Divers lieux, Bruxelles',
    latitude: 50.8503,
    longitude: 4.3517,
    start_date: new Date('2026-01-18T14:00:00').toISOString(),
    end_date: new Date('2026-01-19T02:00:00').toISOString(),
    all_day: false,
    timezone: 'Europe/Brussels',
    cover_image_url: 'https://images.unsplash.com/photo-1511735111819-9a3f7709049c?w=800',
    images: [],
    is_free: true,
    price_min: 0,
    currency: 'EUR',
    is_partner_event: false,
    status: 'published',
    is_featured: true,
    tags: ['jazz', 'music', 'outdoor', 'free'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    published_at: new Date().toISOString(),
    going_count: 127,
    interested_count: 453,
    property_attendees: [
      { id: '1', full_name: 'Marie Dubois', avatar_url: 'https://i.pravatar.cc/150?img=1' },
      { id: '2', full_name: 'Thomas Martin', avatar_url: 'https://i.pravatar.cc/150?img=3' },
      { id: '3', full_name: 'Sophie Laurent', avatar_url: 'https://i.pravatar.cc/150?img=5' },
    ],
  },

  // 2. ESCAPE ROOM - Paid Activity with Partnership
  {
    id: 'evt-2',
    event_type: 'public',
    title: 'The Mystery House - Escape Room',
    description:
      "Plonge dans l'énigme de la Maison Mystère ! Tu as 60 minutes pour résoudre les puzzles et t'échapper. Niveau difficulté : Intermédiaire. Parfait pour un groupe de 4-6 personnes. Notre escape room la plus populaire avec un taux de réussite de 45% !",
    short_description: '60 minutes pour t\'échapper 🔐',
    category_id: 'cat-6',
    category: MOCK_CATEGORIES[5],
    city: 'Bruxelles',
    venue_name: 'Escape Hunt Brussels',
    venue_address: 'Rue du Marché aux Herbes 99, 1000 Bruxelles',
    latitude: 50.8476,
    longitude: 4.3537,
    start_date: new Date('2026-01-15T18:00:00').toISOString(),
    all_day: false,
    timezone: 'Europe/Brussels',
    cover_image_url: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=800',
    images: [],
    is_free: false,
    price_min: 20,
    price_max: 25,
    currency: 'EUR',
    is_partner_event: true,
    partner_name: 'Escape Hunt Brussels',
    partner_logo_url: '/partners/escape-hunt-logo.png',
    promo_code: 'IZZICO20',
    promo_description: '-20% avec le code IZZICO20',
    affiliate_url: 'https://escapehunt.com/brussels?ref=izzico',
    commission_rate: 15,
    status: 'published',
    is_featured: false,
    tags: ['escape-room', 'team-building', 'indoor', 'puzzle'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    published_at: new Date().toISOString(),
    going_count: 12,
    interested_count: 34,
    property_attendees: [
      { id: '2', full_name: 'Thomas Martin', avatar_url: 'https://i.pravatar.cc/150?img=3' },
    ],
  },

  // 3. MUSEUM EXHIBITION - Cultural Event
  {
    id: 'evt-3',
    event_type: 'public',
    title: 'Expo Van Gogh Immersive Experience',
    description:
      "Découvre l'univers de Van Gogh comme jamais auparavant ! Cette exposition immersive utilise la technologie de projection à 360° pour te plonger dans les peintures iconiques de l'artiste. Marche à travers La Nuit Étoilée, Les Tournesols et bien plus. Une expérience sensorielle unique avec musique originale.",
    short_description: 'Immersion totale dans l\'univers de Van Gogh',
    category_id: 'cat-2',
    category: MOCK_CATEGORIES[1],
    city: 'Bruxelles',
    venue_name: 'Brussels Expo',
    venue_address: 'Place de Belgique 1, 1020 Bruxelles',
    latitude: 50.8946,
    longitude: 4.3416,
    start_date: new Date('2026-01-20T10:00:00').toISOString(),
    end_date: new Date('2026-03-31T19:00:00').toISOString(),
    all_day: false,
    timezone: 'Europe/Brussels',
    cover_image_url: 'https://images.unsplash.com/photo-1578301978693-85fa9c0320b9?w=800',
    images: [],
    is_free: false,
    price_min: 15,
    price_max: 22,
    currency: 'EUR',
    is_partner_event: true,
    partner_name: 'Brussels Expo',
    promo_code: 'IZZICO15',
    promo_description: '-15% sur le billet avec IZZICO15',
    external_url: 'https://vangogh-expo.be',
    status: 'published',
    is_featured: true,
    tags: ['art', 'culture', 'immersive', 'indoor'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    published_at: new Date().toISOString(),
    going_count: 89,
    interested_count: 312,
    average_rating: 4.7,
    reviews_count: 156,
  },

  // 4. PROPERTY EVENT - Co-living Team Building
  {
    id: 'evt-4',
    event_type: 'property',
    title: 'Pizza Party - Maison Izzico',
    description:
      "C'est l'heure de se retrouver autour d'une bonne pizza faite maison ! On se retrouve dans le salon pour cuisiner ensemble, rigoler et mieux se connaître. Chacun apporte sa garniture préférée et on teste des combinaisons délirantes. Soirée jeux de société après le repas !",
    short_description: 'Soirée conviviale entre colocataires',
    category_id: 'cat-5',
    category: MOCK_CATEGORIES[4],
    city: 'Bruxelles',
    venue_name: 'Maison Izzico - Salon',
    venue_address: 'Avenue Louise 234, 1050 Bruxelles',
    start_date: new Date('2026-01-17T19:00:00').toISOString(),
    end_date: new Date('2026-01-17T23:00:00').toISOString(),
    all_day: false,
    timezone: 'Europe/Brussels',
    cover_image_url: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800',
    images: [],
    property_id: 'prop-123',
    max_attendees: 12,
    is_free: true,
    price_min: 0,
    currency: 'EUR',
    is_partner_event: false,
    status: 'published',
    is_featured: false,
    tags: ['co-living', 'food', 'social', 'indoor'],
    created_by: 'user-456',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    published_at: new Date().toISOString(),
    going_count: 8,
    interested_count: 3,
  },

  // 5. OUTDOOR SPORTS - Active Event
  {
    id: 'evt-5',
    event_type: 'public',
    title: 'Running Session - Bois de la Cambre',
    description:
      "Rejoins-nous pour une session de running conviviale dans le magnifique Bois de la Cambre ! Tous les niveaux sont les bienvenus. On court ensemble pendant 45min à un rythme tranquille (6-7 min/km), avec des pauses hydratation. Parfait pour rencontrer d'autres runners et découvrir de jolis parcours. Stretching collectif après la course !",
    short_description: 'Course conviviale pour tous niveaux 🏃',
    category_id: 'cat-3',
    category: MOCK_CATEGORIES[2],
    city: 'Bruxelles',
    venue_name: 'Bois de la Cambre - Entrée principale',
    venue_address: 'Avenue Franklin Roosevelt, 1050 Bruxelles',
    latitude: 50.8167,
    longitude: 4.3833,
    start_date: new Date('2026-01-16T07:30:00').toISOString(),
    end_date: new Date('2026-01-16T08:30:00').toISOString(),
    all_day: false,
    timezone: 'Europe/Brussels',
    cover_image_url: 'https://images.unsplash.com/photo-1552674605-db6ffd4facb5?w=800',
    images: [],
    is_free: true,
    price_min: 0,
    currency: 'EUR',
    is_partner_event: false,
    status: 'published',
    is_featured: false,
    tags: ['running', 'outdoor', 'sports', 'morning', 'free'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    published_at: new Date().toISOString(),
    going_count: 23,
    interested_count: 67,
    property_attendees: [
      { id: '1', full_name: 'Marie Dubois', avatar_url: 'https://i.pravatar.cc/150?img=1' },
      { id: '4', full_name: 'Lucas Bernard', avatar_url: 'https://i.pravatar.cc/150?img=8' },
    ],
  },

  // 6. NIGHTLIFE - Bar Event
  {
    id: 'evt-6',
    event_type: 'public',
    title: 'After-Work Networking @ Delirium Café',
    description:
      "Viens networker autour d'une bière belge au mythique Delirium Café ! Ambiance décontractée pour rencontrer des professionnels de tous horizons. Happy Hour jusqu'à 20h (toutes les bières -30%). Ice-breaker games organisés pour briser la glace. Rejoins une communauté de jeunes actifs et expatriés !",
    short_description: 'Networking décontracté avec Happy Hour 🍻',
    category_id: 'cat-4',
    category: MOCK_CATEGORIES[3],
    city: 'Bruxelles',
    venue_name: 'Delirium Café',
    venue_address: 'Impasse de la Fidélité 4, 1000 Bruxelles',
    latitude: 50.8478,
    longitude: 4.3541,
    start_date: new Date('2026-01-16T18:30:00').toISOString(),
    end_date: new Date('2026-01-16T22:00:00').toISOString(),
    all_day: false,
    timezone: 'Europe/Brussels',
    cover_image_url: 'https://images.unsplash.com/photo-1514933651103-005eec06c04b?w=800',
    images: [],
    is_free: true,
    price_min: 0,
    currency: 'EUR',
    is_partner_event: true,
    partner_name: 'Delirium Café',
    promo_description: 'Happy Hour -30% jusqu\'à 20h',
    status: 'published',
    is_featured: false,
    tags: ['networking', 'nightlife', 'social', 'beer'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    published_at: new Date().toISOString(),
    going_count: 45,
    interested_count: 128,
  },

  // 7. WELLNESS - Yoga Session
  {
    id: 'evt-7',
    event_type: 'public',
    title: 'Yoga au Lever du Soleil - Parc Royal',
    description:
      "Commence ta journée en douceur avec une session de yoga gratuite dans le magnifique Parc Royal. Une heure de Vinyasa Flow adaptée à tous les niveaux, guidée par une professeure certifiée. Apporte ton tapis (ou une serviette) et profite de la sérénité du matin. Petit-déjeuner healthy offert après la session !",
    short_description: 'Yoga gratuit avec petit-déj offert 🧘',
    category_id: 'cat-9',
    category: MOCK_CATEGORIES[8],
    city: 'Bruxelles',
    venue_name: 'Parc Royal',
    venue_address: 'Rue Royale, 1000 Bruxelles',
    latitude: 50.8456,
    longitude: 4.3614,
    start_date: new Date('2026-01-19T07:00:00').toISOString(),
    end_date: new Date('2026-01-19T08:30:00').toISOString(),
    all_day: false,
    timezone: 'Europe/Brussels',
    cover_image_url: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800',
    images: [],
    is_free: true,
    price_min: 0,
    currency: 'EUR',
    is_partner_event: false,
    status: 'published',
    is_featured: true,
    tags: ['yoga', 'wellness', 'outdoor', 'morning', 'free'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    published_at: new Date().toISOString(),
    going_count: 56,
    interested_count: 142,
    property_attendees: [
      { id: '5', full_name: 'Emma Petit', avatar_url: 'https://i.pravatar.cc/150?img=9' },
    ],
  },

  // 8. CINEMA - Cultural Event
  {
    id: 'evt-8',
    event_type: 'public',
    title: 'Cinéma en Plein Air - Classics Night',
    description:
      "Soirée nostalgie avec la projection du film culte 'Retour vers le Futur' en plein air ! Ambiance cosy avec couvertures et pop-corn gratuit. Viens avec tes potes ou ta coloc pour revivre ce chef-d'œuvre sur grand écran. Arrivée dès 19h30 pour sécuriser les meilleures places. Bar sur place avec boissons chaudes.",
    short_description: 'Film culte sous les étoiles 🎬',
    category_id: 'cat-8',
    category: MOCK_CATEGORIES[7],
    city: 'Bruxelles',
    venue_name: 'Place Flagey',
    venue_address: 'Place Eugène Flagey, 1050 Bruxelles',
    latitude: 50.8273,
    longitude: 4.3711,
    start_date: new Date('2026-01-22T20:00:00').toISOString(),
    end_date: new Date('2026-01-22T22:30:00').toISOString(),
    all_day: false,
    timezone: 'Europe/Brussels',
    cover_image_url: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=800',
    images: [],
    is_free: true,
    price_min: 0,
    currency: 'EUR',
    is_partner_event: false,
    status: 'published',
    is_featured: false,
    tags: ['cinema', 'outdoor', 'culture', 'free', 'evening'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    published_at: new Date().toISOString(),
    going_count: 178,
    interested_count: 421,
    property_attendees: [
      { id: '1', full_name: 'Marie Dubois', avatar_url: 'https://i.pravatar.cc/150?img=1' },
      { id: '2', full_name: 'Thomas Martin', avatar_url: 'https://i.pravatar.cc/150?img=3' },
      { id: '6', full_name: 'Olivier Rousseau', avatar_url: 'https://i.pravatar.cc/150?img=12' },
      { id: '7', full_name: 'Camille Lefebvre', avatar_url: 'https://i.pravatar.cc/150?img=10' },
    ],
  },

  // 9. FOOD TOUR - Culinary Experience
  {
    id: 'evt-9',
    event_type: 'public',
    title: 'Brussels Food Tour - Saveurs Belges',
    description:
      "Découvre les trésors culinaires de Bruxelles lors d'un food tour de 3h ! Au menu : dégustation de chocolats belges chez un artisan, frites authentiques, bières locales, gaufres et fromages. Un guide passionné te fera découvrir l'histoire gastronomique de la ville. 7 arrêts gourmands au total !",
    short_description: '3h de découvertes culinaires 🧇',
    category_id: 'cat-5',
    category: MOCK_CATEGORIES[4],
    city: 'Bruxelles',
    venue_name: 'Grand-Place (point de départ)',
    venue_address: 'Grand-Place, 1000 Bruxelles',
    latitude: 50.8467,
    longitude: 4.3525,
    start_date: new Date('2026-01-21T14:00:00').toISOString(),
    end_date: new Date('2026-01-21T17:00:00').toISOString(),
    all_day: false,
    timezone: 'Europe/Brussels',
    cover_image_url: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800',
    images: [],
    is_free: false,
    price_min: 45,
    price_max: 45,
    currency: 'EUR',
    is_partner_event: true,
    partner_name: 'Brussels Food Tours',
    promo_code: 'IZZICO10',
    promo_description: '€10 de réduction avec IZZICO10',
    affiliate_url: 'https://brusselsfoodtours.com?ref=izzico',
    commission_rate: 12,
    external_url: 'https://brusselsfoodtours.com',
    status: 'published',
    is_featured: false,
    tags: ['food', 'tour', 'culture', 'guided'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    published_at: new Date().toISOString(),
    going_count: 15,
    interested_count: 48,
    average_rating: 4.9,
    reviews_count: 87,
  },

  // 10. COMMUNITY EVENT - Izzico Organized
  {
    id: 'evt-10',
    event_type: 'community',
    title: 'Izzico Community Meetup',
    description:
      "Rejoins la communauté Izzico pour une soirée networking exclusivement réservée aux membres ! Rencontre d'autres résidents et searchers, partage tes expériences de co-living et fais-toi de nouveaux potes. Cocktails offerts, DJ set et animations surprises. Event organisé par l'équipe Izzico.",
    short_description: 'Networking exclusif membres Izzico',
    category_id: 'cat-10',
    category: MOCK_CATEGORIES[9],
    city: 'Bruxelles',
    venue_name: 'The Hoxton Brussels',
    venue_address: 'Boulevard de Waterloo 38, 1000 Bruxelles',
    latitude: 50.8429,
    longitude: 4.3602,
    start_date: new Date('2026-01-24T19:00:00').toISOString(),
    end_date: new Date('2026-01-24T23:00:00').toISOString(),
    all_day: false,
    timezone: 'Europe/Brussels',
    cover_image_url: 'https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=800',
    images: [],
    is_free: true,
    price_min: 0,
    currency: 'EUR',
    is_partner_event: false,
    status: 'published',
    is_featured: true,
    tags: ['networking', 'community', 'izzico', 'exclusive'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    published_at: new Date().toISOString(),
    going_count: 94,
    interested_count: 187,
  },
];

// ============================================================================
// RECOMMENDED EVENTS - Personalized suggestions
// ============================================================================

export const RECOMMENDED_EVENTS: Event[] = [
  MOCK_EVENTS[0], // Jazz Marathon (popular + free)
  MOCK_EVENTS[6], // Yoga (wellness + free)
  MOCK_EVENTS[9], // Izzico Meetup (community)
];
